### PR TITLE
Update runtime to 22.08

### PR DESCRIPTION
**Pull request by farribeiro**

### CODE REVIEW

**Comment by farribeiro** [comment]
bot, build

**Comment by wjt** [comment]
https://github.com/flathub/org.pulseaudio.pavucontrol/pull/23 will, with luck, address the build failure (which is due to Flathub deploying a stricter linter). If so, we can retry this on top of that.

**Comment by wjt** [comment]
Let's try that a third time!

**Comment by wjt** [comment]
Seems to work. All the fonts got bigger for some unknown reason... Before:

Screenshot from 2022-12-13 13-39-50

After:

Screenshot from 2022-12-13 13-39-56

**Comment by wjt** [comment]
Thanks for the patch!

**Pull request merged**
