### PR TITLE
Update runtime to 19.08

### PR DESCRIPTION
**Pull request by LeandroStanger**

### CODE REVIEW

**Comment by LeandroStanger** [comment]
bot, build org.pulseaudio.pavucontrol

**Comment by LeandroStanger** [comment]
bot, build org.pulseaudio.pavucontrol

**Comment by wjt** [comment]
What's the hurry? As @nedrichards pointed out here https://github.com/flathub/org.pulseaudio.pavucontrol/issues/4#issuecomment-530357089 there is no rush to move away from 18.08. It works fine. We can land this as and when a new pavucontrol release happens.

**Comment by LeandroStanger** [comment]
bot, build org.pulseaudio.pavucontrol

**Pull request closed without merging**
